name: Build Linux

on:
  push:
    paths-ignore:
    - 'LICENSE'
    - 'README.md'
    - '_config.yml'

jobs:
  build:
    name: CI on ${{ matrix.tag }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tag: # Those are alire's dockerhub alire/gnat:tag machines
          - centos-latest-community-2019
          - community-current
          #- debian-stable # disabled ATM, build gets stuck
          - ubuntu-lts # disabled ATM, build gets stuck

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Pull docker image
        run: docker pull alire/gnat:${{ matrix.tag }}
      - name: Build
        run: >
          docker run -v${PWD}:/si_units -w /si_units
          -e "BRANCH=${{ github.base_ref }}"
          alire/gnat:${{ matrix.tag }} bash .github/scripts/ci-build.sh
      - name: Run tests
        run: >
          docker run -v${PWD}:/si_units -w /si_units
          -e "BRANCH=${{ github.base_ref }}"
          alire/gnat:${{ matrix.tag }} bash .github/scripts/ci-test.sh
